# Nombre y puerto independiente
spring.application.name=ms-andesstay-notify
server.port=8083

# Conexión RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Topología de colas y exchanges requerida por el caso
andesstay.rabbitmq.exchange=ex.andesstay.notifications
andesstay.rabbitmq.queue.email=q.cmd.notify.email
andesstay.rabbitmq.queue.sms=q.cmd.notify.sms
andesstay.rabbitmq.queue.push=q.cmd.notify.push
andesstay.rabbitmq.queue.dlq=q.cmd.notify.dlq
andesstay.rabbitmq.exchange.dlx=ex.andesstay.dlx

# Políticas de reintentos y tolerancia a fallos
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=2000ms
spring.rabbitmq.listener.simple.retry.max-attempts=3