spring.application.name=ms-andesstay-catalog
server.port=8082

# Configuración de PostgreSQL (Ajusta usuario, password y nombre de BD a tu entorno)
spring.datasource.url=jdbc:postgresql://localhost:5432/andesstay_catalog
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect