# Puerto del BFF
server.port=8080
spring.application.name=ms-andesstay-bff

# Azure AD (IDaaS)
# Azure AD (IDaaS)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/00d7b2a1-2793-4a06-883e-c37b29134049/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=130c7bbc-6cfa-473f-b953-13c1ef4c2156

# Microservicios internos en Docker Compose
services.reservations.url=http://reservations-svc:8081
services.catalog.url=http://catalog-svc:8082