# Puerto del BFF
server.port=8080
spring.application.name=ms-andesstay-bff

# Azure AD (IDaaS) - Rúbrica: issuer y audience
# Reemplaza AZURE_TENANT_ID y AZURE_CLIENT_ID con tus variables o valores directos
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID:common}/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://${AZURE_CLIENT_ID:andesstay-api-client-id}

# Enlace al microservicio interno de reservas
services.reservations.url=http://localhost:8081