server.port=8081
spring.application.name=ms-andesstay-reservations

# Conexión Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.[TU-PROYECTO-REF].supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=[TU-PASSWORD]
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true