spring.application.name=backend
server.port=8080

# Habilitar integración con Azure AD
spring.cloud.azure.active-directory.enabled=true

# Identificadores de Azure AD / Entra ID
spring.cloud.azure.active-directory.profile.tenant-id=11c155d4-cb07-4f55-9826-c914bd1fba9a
spring.cloud.azure.active-directory.credential.client-id=ea1d880b-4375-41bd-afd9-a9cb82e88711

# Application ID URI configurado en "Exponer una API"
spring.cloud.azure.active-directory.app-id-uri=api://ea1d880b-4375-41bd-afd9-a9cb82e88711

# Validación del emisor del token JWT (Issuer)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/b19dac1c-44c9-4e15-9214-59ae9f63b92e/v2.0